services:
  mysql:
    image: mysql:8.4
    container_name: exam-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # root 用户密码
      MYSQL_ROOT_PASSWORD: 123456
      # 创建的数据库名称
      MYSQL_DATABASE: exam_registration_system
      # 字符集
      TZ: Asia/Shanghai
    volumes:
      # 数据持久化
      - ./data/mysql:/var/lib/mysql
      # 初始化SQL脚本（容器首次启动时自动执行）
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - exam-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exam-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/exam_registration_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mysql
    networks:
      - exam-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exam-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - exam-network

networks:
  exam-network:
    driver: bridge
