services:
  mysql:
    image: mysql:8.4
    container_name: exam-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # root 用户密码
      MYSQL_ROOT_PASSWORD: 123456
      # 创建的数据库名称
      MYSQL_DATABASE: exam_registration_system
      # 字符集
      TZ: Asia/Shanghai
    volumes:
      # 数据持久化
      - ./data/mysql:/var/lib/mysql
      # 初始化SQL脚本（容器首次启动时自动执行）
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - exam-network

networks:
  exam-network:
    driver: bridge
